#!/usr/bin/env bash

# Inspired on https://github.com/adriancooney/Taskfile
#
# Install an alias, to be able to simply execute `run`
# echo 'alias run=./scripts/run' >> ~/.aliases
#
set -e

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function default {
  help
}

function secret:generate {
  openssl rand -base64 64 | tr -d '\n' ; echo
}

function start {
  docker compose up -d --remove-orphans
}

function stop {
  docker compose down
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"
